app:
  Name: go-echo-example
  Version: 1.0.0
  Debug: true
  Addr: :8081
  Timeout: 5

logger:
  LoggerFilePath: ../tmp/log
  LogRotateDate: 1
  LogRotateSize: 1
  LogBackupCount: 7
  Compress: true

db:
  Driver: "mysql"
  Name: test                     # 数据库名称
  Addr: 127.0.0.1:3306            # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  UserName: root
  Password: root
  ShowLog: true                   # 是否打印SQL日志
  MaxIdleConn: 10                 # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 60                 # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime: 60m            # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些
  TimeZone: "Asia%2fShanghai"
  Charset: utf8mb4

redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
  MinIdleConn: 200
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 12000
  PoolTimeout: 240

email:
  Host: SMTP_HOST       # SMTP地址
  Port: 25              # 端口
  Username: USER        # 用户名
  Password: PASSWORD    # 密码
  Name: snake           # 发送者名称
  Address: SEND_EMAIL   # 发送者邮箱
  ReplyTo: EMAIL       # 回复地址
  KeepAlive: 30         # 连接保持时长